jobs:
- job:
  timeoutInMinutes: 240
  displayName: Ubuntu Bionic
  pool:
    vmImage: 'ubuntu-18.04'

  variables:
    UBUNTU_CODE_NAME: bionic
    BOOST_VERSION: boost_1_70_0
    BOOST_DIR: $(Pipeline.Workspace)/boost
    CCACHE_DIR: $(Pipeline.Workspace)/ccache
    CCACHE_COMPRESS: 1
    CCACHE_COMPRESSLEVEL: 9
    CCACHE_CPP2: 1
    CCACHE_MAXSIZE: 2G

  strategy:
    matrix:
      Clang-10 Debug:
        Compiler: clang
        CompilerVer: 10
        BuildType: Debug

      Clang-10 Release:
        Compiler: clang
        CompilerVer: 10
        BuildType: RelWithDebInfo

      GCC-9 Debug:
        Compiler: gcc
        CompilerVer: 9
        BuildType: Debug

      GCC-9 Release:
        Compiler: gcc
        CompilerVer: 9
        BuildType: RelWithDebInfo

      Clang-9 Debug:
        Compiler: clang
        CompilerVer: 9
        BuildType: Debug

      Clang-9 Release:
        Compiler: clang
        CompilerVer: 9
        BuildType: RelWithDebInfo

      GCC-8 Debug:
        Compiler: gcc
        CompilerVer: 8
        BuildType: Debug

      GCC-8 Release:
        Compiler: gcc
        CompilerVer: 8
        BuildType: RelWithDebInfo

      Clang-8 Debug:
        Compiler: clang
        CompilerVer: 8
        BuildType: Debug

      Clang-8 Release:
        Compiler: clang
        CompilerVer: 8
        BuildType: RelWithDebInfo

      GCC-7 Debug:
        Compiler: gcc
        CompilerVer: 7
        BuildType: Debug

      GCC-7 Release:
        Compiler: gcc
        CompilerVer: 7
        BuildType: RelWithDebInfo

      Clang-7 Debug:
        Compiler: clang
        CompilerVer: 7
        BuildType: Debug

      Clang-7 Release:
        Compiler: clang
        CompilerVer: 7
        BuildType: RelWithDebInfo

      GCC-6 Debug:
        Compiler: gcc
        CompilerVer: 6
        BuildType: Debug

      GCC-6 Release:
        Compiler: gcc
        CompilerVer: 6
        BuildType: RelWithDebInfo

      Clang-6 Debug:
        Compiler: clang
        CompilerVer: 6.0
        BuildType: Debug

      Clang-6 Release:
        Compiler: clang
        CompilerVer: 6.0
        BuildType: RelWithDebInfo

      GCC-5 Debug:
        Compiler: gcc
        CompilerVer: 5
        BuildType: Debug

      GCC-5 Release:
        Compiler: gcc
        CompilerVer: 5
        BuildType: RelWithDebInfo

      Clang-5 Debug:
        Compiler: clang
        CompilerVer: 5.0
        BuildType: Debug

      Clang-5 Release:
        Compiler: clang
        CompilerVer: 5.0
        BuildType: RelWithDebInfo

  steps:
  - script: |
      uname -r
      df -Th

    displayName: '*** Compile'
